### ISSUE TITLE
AttributeError: 'DistributedDataParallel' object has no attribute 'parent'

### ISSUE THREAD

**Issue by egorsmkv** [pashanitw/xeus-finetune#2]
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/yehor/ext-ml-disk/experiments/xeus-finetune/finetune.py", line 357, in <module>
[rank0]:     accelerator.clip_grad_norm_(model.parent.parameters(), config.max_grad_norm)
[rank0]:                                 ^^^^^^^^^^^^
[rank0]:   File "/home/yehor/ext-ml-disk/experiments/xeus-finetune/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
[rank0]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank0]: AttributeError: 'DistributedDataParallel' object has no attribute 'parent'
```

**Comment by pashanitw** [comment]
fixed in the latest commit
